In [3]:
import numpy as np
#Always use `np.array` in order to create an array because it infers `dtype` correctly!
#array_1 = np.array([1,2,3], dtype=np.int8) #(1,)
array_1 = np.array([[1,2,3], [4,5,6]], dtype=np.int8) #(3,1)

print(array_1.strides) #strides define how many bytes one need to traverse in order to get next element for each dimension

(3, 1)


In [4]:
nd_array1 = np.ndarray((2, 2)) #pass dimension of matrix to be generated - ndarray will populate with random numbers
print(nd_array1) 
'''[[2.12199579e-314 9.99460018e-312]
   [4.30825243e-321 6.95293141e-310]]'''

[[2.12199579e-314 1.44932313e-311]
 [5.31614635e-321 6.95314361e-310]]


'[[2.12199579e-314 9.99460018e-312]\n   [4.30825243e-321 6.95293141e-310]]'

In [5]:
# Defining arrays
arr1d_int = np.array([1, 2, 3, 4])
arr2d_float = np.array(((1, 2, 3, 4), (5, 6, 7, 8.0)))  # Notice 8.0

print(arr1d_int)
print(arr2d_float)
arr1d_int.dtype, type(arr1d_int), arr2d_float.dtype, type(arr2d_float) 
#(dtype('int32'), numpy.ndarray, dtype('float64'), numpy.ndarray)

[1 2 3 4]
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(dtype('int32'), numpy.ndarray, dtype('float64'), numpy.ndarray)

In [6]:
# Explain values below based on the code and output
arr = np.arange(9).reshape(3, 3)

print(arr)
'''[[0 1 2]
   [3 4 5]
   [6 7 8]]'''
print(f'The data type of each element is: {arr.dtype}') #int32
print(f'The length of each element in bytes is: {arr.itemsize}') #4
print(f'The strides of the data types is: {arr.strides}') #(12,4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
The data type of each element is: int32
The length of each element in bytes is: 4
The strides of the data types is: (12, 4)


In [7]:
matrix = np.arange(20).reshape(5, 4) #5 = number of rows, 4 = number of columns

matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
# Obtaining single element - rows and elements start at 0
matrix[0, 0], matrix[1, 0], matrix[0, 1], matrix[2][0] #(0,4,1,8)

(0, 4, 1, 8)

In [9]:
# : means all elements
# 0 means 0th column

matrix[:, 0] #array([ 0,  4,  8, 12, 16])

array([ 0,  4,  8, 12, 16])

In [10]:
# Shuffle rows using indices

indices = np.arange(matrix.shape[0])
print(indices)
permuted = np.random.permutation(indices)
print(permuted)

matrix[permuted]

[0 1 2 3 4]
[4 1 0 3 2]


array([[16, 17, 18, 19],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [11]:
np.random.rand(1,24).reshape(4, 6) #numbers in range are multiplied to fit into grid size specified in reshape()

array([[0.14225545, 0.70889694, 0.05366056, 0.27529118, 0.51920662,
        0.12284669],
       [0.09877536, 0.78961925, 0.47357672, 0.82568889, 0.97844463,
        0.20671197],
       [0.87353187, 0.96340053, 0.46373248, 0.76500401, 0.26729851,
        0.37650197],
       [0.01467683, 0.83194843, 0.92785616, 0.99202688, 0.1221233 ,
        0.83731191]])

In [12]:
import random
matrix1 = np.random.randn(24).reshape(4, 6) #4 = number of rows, 6 = number of columns

matrix1

array([[-0.74920541, -1.50671549, -0.53322925, -0.15662477,  0.49281523,
         0.53392749],
       [ 1.73557449,  0.21938696,  0.32921478,  1.05525583,  1.38820102,
         1.97851486],
       [ 0.23700007, -0.91247467, -1.58890803, -0.39546792, -2.32158363,
        -1.02816862],
       [-1.43070427, -0.82216427,  0.82121477, -0.02860913,  1.60049147,
        -1.05539115]])

In [13]:
matrix1[2,1] #index element on 3rd row, 2nd column (rows and elements start at 0)


-0.9124746746423427

In [14]:
matrix1[0:5,1] #prints elements in 2nd column

array([-1.50671549,  0.21938696, -0.91247467, -0.82216427])

In [15]:
matrix1[0:5,0:2] #prints elements in first 2 columns

array([[-0.74920541, -1.50671549],
       [ 1.73557449,  0.21938696],
       [ 0.23700007, -0.91247467],
       [-1.43070427, -0.82216427]])

In [16]:
matrix1[0:5,0:4] #prints elements in first 4 columns

array([[-0.74920541, -1.50671549, -0.53322925, -0.15662477],
       [ 1.73557449,  0.21938696,  0.32921478,  1.05525583],
       [ 0.23700007, -0.91247467, -1.58890803, -0.39546792],
       [-1.43070427, -0.82216427,  0.82121477, -0.02860913]])

In [17]:
matrix1[0:5,0:2] #prints elements in first 2 columns

array([[-0.74920541, -1.50671549],
       [ 1.73557449,  0.21938696],
       [ 0.23700007, -0.91247467],
       [-1.43070427, -0.82216427]])

In [18]:
matrix1[:2] #prints elements in first 2 rows

array([[-0.74920541, -1.50671549, -0.53322925, -0.15662477,  0.49281523,
         0.53392749],
       [ 1.73557449,  0.21938696,  0.32921478,  1.05525583,  1.38820102,
         1.97851486]])

In [19]:
matrix1[:1,:3] #prints first 3 elements in 1st row

array([[-0.74920541, -1.50671549, -0.53322925]])

In [20]:
matrix1[::2] #index elements in rows 1 and 2

array([[-0.74920541, -1.50671549, -0.53322925, -0.15662477,  0.49281523,
         0.53392749],
       [ 0.23700007, -0.91247467, -1.58890803, -0.39546792, -2.32158363,
        -1.02816862]])

In [21]:
matrix1[1:3] #index elements in rows 2 and 3

array([[ 1.73557449,  0.21938696,  0.32921478,  1.05525583,  1.38820102,
         1.97851486],
       [ 0.23700007, -0.91247467, -1.58890803, -0.39546792, -2.32158363,
        -1.02816862]])

In [22]:
matrix1[1::2] #index all even rows

array([[ 1.73557449,  0.21938696,  0.32921478,  1.05525583,  1.38820102,
         1.97851486],
       [-1.43070427, -0.82216427,  0.82121477, -0.02860913,  1.60049147,
        -1.05539115]])

In [23]:
matrix1[0::3] #index first and last rows

array([[-0.74920541, -1.50671549, -0.53322925, -0.15662477,  0.49281523,
         0.53392749],
       [-1.43070427, -0.82216427,  0.82121477, -0.02860913,  1.60049147,
        -1.05539115]])

Slice syntax => i:j:k

i = starting index
j = stopping index
k = step k ≠ 0

In [24]:
matrix1[0:3:2] #index elements in rows 1 and 3 (odd rows) - i:j:k

array([[-0.74920541, -1.50671549, -0.53322925, -0.15662477,  0.49281523,
         0.53392749],
       [ 0.23700007, -0.91247467, -1.58890803, -0.39546792, -2.32158363,
        -1.02816862]])

In [25]:
matrix1[1:4:3]

array([[1.73557449, 0.21938696, 0.32921478, 1.05525583, 1.38820102,
        1.97851486]])

In [35]:
matrix1.diagonal() #prints diagonal elements in matrix

array([-0.74920541,  0.21938696, -1.58890803, -0.02860913])